name: Ruff Lint and Format Check

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check"
          src: "."
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
          src: "."
